name: Proxy Updater

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  proxy_updater:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install pycountry
    - name: Remove old proxies
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.SMTHNG_SCRT }}
    - run: |
        rm http.txt
        rm socks4.txt
        rm socks5.txt
    - name: Scrape new proxies
      run: |
        git clone ${{ secrets.UPDATER }}
        cd xcraper
        bash scraper.sh
    - name: Update new proxies
      run: bash updater.sh
